FROM python:3.7-stretch

WORKDIR /home/app

RUN apt-get update

RUN pip install pandas
RUN pip install sqlalchemy
RUN pip install argparse
RUN pip install psycopg2
RUN pip install xlrd
RUN pip install openpyxl